const products = [
  {
    id: 1,
    title: "OPPO A37f",
    description: "Good product with excellent quality",
    price: 230.0,
    image: "imgs/phone-1.jpg",
    altText: "phone-1",
  },
  {
    id: 2,
    title: "OPPO A37f",
    description: "Good product with excellent quality",
    price: 230.0,
    image: "imgs/phone-2.jpg",
    altText: "phone-2",
  },
  {
    id: 3,
    title: "OPPO A37f",
    description: "Good product with excellent quality",
    price: 230.0,
    image: "imgs/phone-3.jpg",
    altText: "phone-3",
  },
  {
    id: 4,
    title: "OPPO A37f",
    description: "Good product with excellent quality",
    price: 230.0,
    image: "imgs/phone-4.jpg",
    altText: "phone-4",
  },
  {
    id: 5,
    title: "OPPO A37f",
    description: "Good product with excellent quality",
    price: 230.0,
    image: "imgs/phone-5.jpg",
    altText: "phone-5",
  },
  {
    id: 6,
    title: "OPPO A37f",
    description: "Good product with excellent quality",
    price: 230.0,
    image: "imgs/phone-6.jpg",
    altText: "phone-6",
  },
  {
    id: 7,
    title: "Havit Headphone",
    description: "Model Number: SD-1004",
    price: 445.0,
    image: "imgs/headphone-1.jpg",
    altText: "headphone-1",
  },
  {
    id: 8,
    title: "Havit Headphone",
    description: "Model Number: SD-1004",
    price: 445.0,
    image: "imgs/headphone-2.jpg",
    altText: "headphone-2",
  },
  {
    id: 9,
    title: "Havit Headphone",
    description: "Model Number: SD-1004",
    price: 445.0,
    image: "imgs/headphone-3.jpg",
    altText: "headphone-3",
  },
];
